# Generated by Django 3.0.3 on 2020-02-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=1000)),
                ('option_a', models.CharField(max_length=100)),
                ('option_b', models.CharField(max_length=100)),
                ('option_c', models.CharField(max_length=100)),
                ('option_d', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('question_maker_id', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('verification_status', models.BooleanField()),
            ],
        ),
    ]
