# Generated by Django 3.0.3 on 2020-02-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200217_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='types',
        ),
        migrations.AddField(
            model_name='question',
            name='type1',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
