# Generated by Django 3.0.3 on 2020-02-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200217_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_maker_id',
            field=models.CharField(max_length=50),
        ),
    ]
