# Generated by Django 3.0.3 on 2020-02-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='fid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
