# Generated by Django 3.0.3 on 2020-02-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_fileupload_fid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='fid',
        ),
    ]
