# Generated by Django 3.0.3 on 2020-02-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_remove_fileupload_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file1',
            field=models.FileField(upload_to='pics/'),
        ),
    ]
