# Generated by Django 3.0.3 on 2020-03-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20200306_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
    ]
