# Generated by Django 3.0.3 on 2020-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_remove_myuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resopnse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Myuser',
        ),
    ]
