# Generated by Django 3.0.3 on 2020-03-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20200311_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resopnse',
        ),
    ]
