# Generated by Django 3.0.3 on 2020-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_delete_resopnse'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='verification_status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
