# Generated by Django 3.0.3 on 2020-03-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_fileupload_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='null', max_length=1000)),
                ('option_a', models.CharField(default='null', max_length=100)),
                ('option_b', models.CharField(default='null', max_length=100)),
                ('option_c', models.CharField(default='null', max_length=100)),
                ('option_d', models.CharField(default='null', max_length=100)),
                ('answer', models.CharField(default='null', max_length=100)),
                ('response', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
