# Generated by Django 3.0.3 on 2020-03-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
