# Generated by Django 3.0.3 on 2020-03-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_store_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
