# Generated by Django 3.0.3 on 2020-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_auto_20200312_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='option_a',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='option_b',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='option_c',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='option_d',
            field=models.BooleanField(),
        ),
    ]
