# Generated by Django 3.0.3 on 2020-03-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_auto_20200312_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='student',
            field=models.IntegerField(null=True),
        ),
    ]
