# Generated by Django 3.0.3 on 2020-03-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_auto_20200318_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
