# Generated by Django 3.0.3 on 2020-03-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_auto_20200319_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
