# Generated by Django 3.0.3 on 2020-05-28 18:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('exam_name', models.CharField(default='null', max_length=100)),
                ('easy', models.IntegerField(null=True)),
                ('medium', models.IntegerField(null=True)),
                ('hard', models.IntegerField(null=True)),
                ('marks', models.IntegerField(null=True)),
                ('exam_date', models.DateField(null=True)),
                ('immediate', models.BooleanField()),
                ('start_time', models.TimeField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('cutoff', models.IntegerField(null=True)),
                ('centre_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
