# Generated by Django 3.0.3 on 2020-05-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0002_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centreque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField(null=True)),
                ('question_id', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('type1', models.CharField(max_length=20, null=True)),
                ('difficulty', models.CharField(max_length=20, null=True)),
                ('question', models.CharField(max_length=100, null=True)),
                ('option_a', models.CharField(max_length=20, null=True)),
                ('option_b', models.CharField(max_length=20, null=True)),
                ('option_c', models.CharField(max_length=20, null=True)),
                ('option_d', models.CharField(max_length=20, null=True)),
                ('answer', models.CharField(max_length=20, null=True)),
                ('img', models.ImageField(upload_to='pics/')),
            ],
        ),
    ]
