# Generated by Django 3.0.3 on 2020-05-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0003_centreque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examresponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField(null=True)),
                ('question', models.CharField(default='null', max_length=1000)),
                ('answer', models.CharField(default='null', max_length=100)),
                ('response', models.CharField(default='null', max_length=100)),
                ('button', models.CharField(default='null', max_length=10)),
                ('question_id', models.IntegerField()),
                ('student_id', models.CharField(default='null', max_length=20)),
                ('response_id', models.IntegerField(null=True)),
            ],
        ),
    ]
