# Generated by Django 3.0.3 on 2020-05-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0004_examresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Centre',
        ),
        migrations.DeleteModel(
            name='Centreque',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Examresponse',
        ),
    ]
