# Generated by Django 3.0.3 on 2020-05-28 19:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newadmin', '0005_auto_20200529_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Centreque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField(null=True)),
                ('question_id', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('type1', models.CharField(max_length=20, null=True)),
                ('difficulty', models.CharField(max_length=20, null=True)),
                ('question', models.CharField(max_length=100, null=True)),
                ('option_a', models.CharField(max_length=20, null=True)),
                ('option_b', models.CharField(max_length=20, null=True)),
                ('option_c', models.CharField(max_length=20, null=True)),
                ('option_d', models.CharField(max_length=20, null=True)),
                ('answer', models.CharField(max_length=20, null=True)),
                ('img', models.ImageField(upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('exam_name', models.CharField(default='null', max_length=100)),
                ('easy', models.IntegerField(null=True)),
                ('medium', models.IntegerField(null=True)),
                ('hard', models.IntegerField(null=True)),
                ('marks', models.IntegerField(null=True)),
                ('exam_date', models.DateField(null=True)),
                ('immediate', models.BooleanField()),
                ('start_time', models.TimeField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('cutoff', models.IntegerField(null=True)),
                ('centre_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Examresponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField(null=True)),
                ('question', models.CharField(default='null', max_length=1000)),
                ('answer', models.CharField(default='null', max_length=100)),
                ('response', models.CharField(default='null', max_length=100)),
                ('button', models.CharField(default='null', max_length=10)),
                ('question_id', models.IntegerField()),
                ('student_id', models.CharField(default='null', max_length=20)),
                ('response_id', models.IntegerField(null=True)),
            ],
        ),
    ]
