# Generated by Django 3.0.3 on 2020-05-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0006_centre_centreque_exam_examresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreque',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centreque',
            name='option_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centreque',
            name='option_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centreque',
            name='option_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centreque',
            name='option_d',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='centreque',
            name='question',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
