# Generated by Django 3.0.3 on 2020-05-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newadmin', '0007_auto_20200529_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresponse',
            name='mark',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresponse',
            name='type1',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
