# Generated by Django 3.0.3 on 2020-03-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='null', max_length=1000)),
                ('option_a', models.BooleanField()),
                ('option_b', models.BooleanField()),
                ('option_c', models.BooleanField()),
                ('option_d', models.BooleanField()),
                ('answer', models.CharField(default='null', max_length=100)),
                ('response', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
