# Generated by Django 3.0.3 on 2020-03-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='student_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
