# Generated by Django 3.0.3 on 2020-03-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0002_response_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='student_id',
        ),
    ]
