# Generated by Django 3.0.3 on 2020-03-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0003_remove_response_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='response',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='response',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='response',
            name='option_d',
        ),
    ]
