# Generated by Django 3.0.3 on 2020-03-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0004_auto_20200312_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='button',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
