# Generated by Django 3.0.3 on 2020-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0005_response_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='question_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
