# Generated by Django 3.0.3 on 2020-03-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0008_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('type1', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=1000)),
                ('option_a', models.CharField(max_length=100)),
                ('option_b', models.CharField(max_length=100)),
                ('option_c', models.CharField(max_length=100)),
                ('option_d', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('question_maker_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('verification_status', models.BooleanField()),
                ('img', models.ImageField(upload_to='media/pics/')),
            ],
        ),
    ]
