# Generated by Django 3.0.3 on 2020-03-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0009_question1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question1',
            name='img',
            field=models.ImageField(upload_to='media\\pics/'),
        ),
    ]
