# Generated by Django 3.0.3 on 2020-03-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0014_delete_question1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='null', max_length=20)),
                ('time', models.IntegerField(default='null')),
            ],
        ),
    ]
