# Generated by Django 3.0.3 on 2020-03-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0017_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='qualify',
        ),
        migrations.AddField(
            model_name='result',
            name='img',
            field=models.ImageField(default='null', upload_to='pics/'),
        ),
    ]
