# Generated by Django 3.0.3 on 2020-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0018_auto_20200327_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='null', max_length=50)),
                ('first_name', models.CharField(default='null', max_length=50)),
                ('last_name', models.CharField(default='null', max_length=50)),
                ('score', models.IntegerField(default='null')),
            ],
        ),
    ]
