# Generated by Django 3.0.3 on 2020-05-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0019_immediate'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_id',
            field=models.IntegerField(null=True),
        ),
    ]
