# Generated by Django 3.0.3 on 2020-05-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0020_response_response_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='type1',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
