# Generated by Django 3.0.3 on 2020-04-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(max_length=30, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('type1', models.CharField(max_length=20, null=True)),
                ('difficulty', models.CharField(max_length=20, null=True)),
                ('question', models.CharField(max_length=100, null=True)),
                ('option_a', models.CharField(max_length=20, null=True)),
                ('option_b', models.CharField(max_length=20, null=True)),
                ('option_c', models.CharField(max_length=20, null=True)),
                ('option_d', models.CharField(max_length=20, null=True)),
                ('accepted_ans', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
