# Generated by Django 3.0.3 on 2020-04-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(default=False, max_length=20)),
                ('name', models.CharField(default=False, max_length=20)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
