# Generated by Django 3.0.3 on 2020-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0003_auto_20200417_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(null=True),
        ),
    ]
