# Generated by Django 3.0.3 on 2020-05-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0005_verifier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Cquestion',
        ),
    ]
