# Generated by Django 3.0.3 on 2020-05-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0006_auto_20200507_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='dob',
            field=models.DateField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='idprof',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pic',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
