# Generated by Django 3.0.3 on 2020-05-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0007_auto_20200525_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='start',
            field=models.TimeField(null=True),
        ),
    ]
