# Generated by Django 3.0.3 on 2020-05-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0008_auto_20200526_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifier',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verifier',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='verifier',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
