# Generated by Django 3.0.3 on 2020-05-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0010_cquestion_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cquestion',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cquestion',
            name='option_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cquestion',
            name='option_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cquestion',
            name='option_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cquestion',
            name='option_d',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cquestion',
            name='question',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
