# Generated by Django 3.0.3 on 2020-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0011_auto_20200529_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cexamdt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField(null=True)),
                ('marks', models.IntegerField(null=True)),
                ('exam_date', models.DateField(null=True)),
                ('immediate', models.BooleanField()),
                ('start_time', models.TimeField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('cutoff', models.IntegerField(null=True)),
            ],
        ),
    ]
