# Generated by Django 3.0.3 on 2020-04-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatereg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='centre_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='exam_id',
            field=models.IntegerField(null=True),
        ),
    ]
