# Generated by Django 3.0.3 on 2020-05-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatereg', '0003_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sig',
        ),
    ]
