# Generated by Django 3.0.3 on 2020-05-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatereg', '0005_student_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idprof',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
